name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Typecheck Test Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v3

      - run: pnpm install --frozen-lockfile

      - run: pnpm typecheck

      - run: pnpm test

      - run: pnpm format

      - run: pnpm build
